#!/usr/bin/env bash

echo "=== Installing DNF Packages ==="
dnf install hyprland # for tiling window system
dnf copr enable solopasha/hyprland # required to access some hyprland dnf modules
dnf install hyprshot # for screenshots
dnf install hyprlock # for locking the screen
dnf install hypridle # for locking the screen when idle
dnf install hyprpaper # for desktop wallpaper
dnf install waybar # for hyprland top bar module
def install swaync # for notification center. Gets notifications from Gnome's lib-notify
dnf copr enable ghostty
dnf install ghostty # for my terminal emulator of choice
dnf install wofi # for spotlight-like search menu
dnf install zsh
dnf install starship
dnf copr enable chronoscrat/oh-my-posh
dnf install --refresh oh-my-posh
dnf install neovim
dnf install gh
dnf install gtk-murrine-engine # for themes
dnf install sassc # also for themes
dnf install gnome-themes-extra # yup, themes
dnf install gnome-tweaks # uh huh, you guessed it.

# This is for enabling themes. Specifically, enabling
# the theming for flatpaks. These were taking from here:
# @url: https://github.com/Fausto-Korpsvart/Kanagawa-GKT-Theme
flatpak override --filesystem=$HOME/.themes # Override flatpak themes to ~/.themes
flatpak override --filesystem=$HOME/.icons # Override flatpak icons to ~/.icons:
flatpak override --user --filesystem=xdg-config/gtk-4.0 # Override flatpak themes to ~/.config/gtk-4.0 locally:
flatpak override --filesystem=xdg-config/gtk-4.0 # Override flatpak themes to ~/.config/gtk-4.0 globally:

# This is for programming keyboard keys, like making
# CapsLock both Esc and Ctrl, a combination which is
# not possible using hyprland's XKB settings alone.
# See `keyd/default.conf`
# file for my custom configurations.
# @url: https://github.com/rvaiya/keyd
mkdir /etc/keyd
dnf copr enable alternateved/keyd
dnf install keyd
systemctl enable --now keyd
# Run `systemctl status keyd` to see the daemon status.
# Run `journalctl -eu keyd` to see the logs.
#
# Note: Changes to the config might not be recognized
# until a `sudo keyd reload` is performed.
