#!/usr/bin/env bash

echo "=== Installing DNF Packages ==="
dnf install hyprland # for tiling window system
dnf copr enable solopasha/hyprland # required to access some hyprland dnf modules
dnf install hyprshot # for screenshots
dnf install hyprlock # for locking the screen
dnf install hypridle # for locking the screen when idle
dnf install hyprpaper # for desktop wallpaper
dnf install waybar # for hyprland top bar module
def install swaync # for notification center. Gets notifications from Gnome's lib-notify
dnf copr enable ghostty
dnf install ghostty # for my terminal emulator of choice
dnf install wofi # for spotlight-like search menu
dnf install zsh
dnf install starship # I tried it out, I'm not sure I'll keep this...
dnf copr enable chronoscrat/oh-my-posh
dnf install --refresh oh-my-posh # Alternative to ohmyzsh. I like it, despite lacking omz's aliases
dnf install neovim
dnf install gh
dnf install gtk-murrine-engine # for themes
dnf install sassc # also for themes
dnf install gnome-themes-extra # yup, themes
dnf install gnome-tweaks # uh huh, you guessed it.
dnf install rust cargo # Install Rust package manager
dnf install rustup # Install Rust itself via rustup

echo "=== installing flatpak and adding support for themes ==="
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
# The below are for enabling themes. Specifically, enabling
# the theming for flatpaks. These were taking from here:
# @url: https://github.com/Fausto-Korpsvart/Kanagawa-GKT-Theme
flatpak override --filesystem=$HOME/.themes # Override flatpak themes to ~/.themes
flatpak override --filesystem=$HOME/.icons # Override flatpak icons to ~/.icons:
flatpak override --user --filesystem=xdg-config/gtk-4.0 # Override flatpak themes to ~/.config/gtk-4.0 locally:
flatpak override --filesystem=xdg-config/gtk-4.0 # Override flatpak themes to ~/.config/gtk-4.0 globally:

echo "=== Installing packages for theming Hyprland ==="
cargo install matugen

# This is a fix for getting my cursor theme to work. The
# usual advice was not work (ex. use Gnome Tweaks to set
# the cursor theme). So instead, I'm doing it via a combo
# of hyprland configuration plus the following command.
# This trick courtesy of:
# @url: https://bbs.archlinux.org/viewtopic.php?id=302459
echo "=== Fix and apply cursor theme via Hyprland ==="
hyprctl setcursor Bibata-Modern-Classic 24

# This is for programming keyboard keys, like making
# CapsLock both Esc and Ctrl, a combination which is
# not possible using hyprland's XKB settings alone.
# See `keyd/default.conf`
# file for my custom configurations.
# @url: https://github.com/rvaiya/keyd
echo "=== Setting up keyboard customizations and mappings ==="
mkdir /etc/keyd
dnf copr enable alternateved/keyd
dnf install keyd
systemctl enable --now keyd
# Run `systemctl status keyd` to see the daemon status.
# Run `journalctl -eu keyd` to see the logs.
#
# Note: Changes to the config might not be recognized
# until a `sudo keyd reload` is performed.

# Add support for Dropbox to Nautilus. See here:
# @url: https://github.com/dropbox/nautilus-dropbox
# Might not actually be necessary? It's unclear...
# echo "=== Setting up Dropbox Nautilus plugin ==="
# dnf install -y gnome-common nautilus-devel gtk4-devel python3-docutils

# Add support for a command line music player: rmpc (Rust Music Player)
#
# Prerequisite rmpfusion, for extra media formats.
dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
#
# Prerequisite: MPD. Installation steps taken from...
# @URL: https://fedoramagazine.org/playing-music-on-your-fedora-terminal-with-mpd-and-ncmpcpp/
dnf install mpd # run with just `mpd`, and/or `systemctl start mpd`
dnf install mpDris2 # this adds support for mpd meta access to mpris for displaying songs in widgets
#
# @URL: https://mierak.github.io/rmpc
cargo install rmpc --locked
