#!/usr/bin/env bash

set -e

echo "== Installing packages ==="
brew install neovim
brew install fsouza/prettierd/prettierd
brew install ripgrep
brew install --cask alt-tab # https://alt-tab-macos.netlify.app/
brew install sequel-ace # https://sequel-ace.com/
brew install --cask ghostty # https://formulae.brew.sh/cask/ghostty
brew install --cask obsidian # https://formulae.brew.sh/cask/obsidian

echo "=== Installing ripgrep, a dependency of Telescope live-grep ==="
sudo apt-get install ripgrep
