#!/usr/bin/env bash

# Firefox
# Dropbox
# Keyd
# zsh

# oh-my-zsh
# Install this for the plugins, like diretories, history, etc.
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# ohmyposh
curl -s https://ohmyposh.dev/install.sh | bash -s
